### ISSUE TITLE
Ubo Open Source Hardware 

### ISSUE THREAD

**Issue by ubopod** [OpenInterpreter/01#10]
Just wanted to bring Ubo Pod OSS hardware to light in case it might be of an interest. It is based on Raspberry Pi with a polished UX. I have already made a few hundred of these but can ramp production if there is interest. The complete source code and design files are published below:

https://github.com/ubopod
https://getubo.com
https://hackaday.io/project/190742-ubo-pod-build-apps-with-rich-ux-on-raspberry-pi

I am currently working on Raspberry Pi 5 support with NVMe which is the way to go for running large LLM models.

**Comment by tyfiero** [comment]
Thanks for bringing this up! You are welcome to add support for the ubo pod device in the repository.
