### ISSUE TITLE
Application shutting down on startup

### ISSUE THREAD

**Issue by zepef** [OpenInterpreter/01#105]
**Describe the bug**
The poetry install was OK. I ran poetry run 01 --local, starting message is displauyed and then it hangs and exits from PowerShell.

**Error messages**

(base) PS F:\katas\01\software> poetry run 01 --local

○

Starting...

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ F:\Katas\01\software\start.py:43 in run                                                          │
│                                                                                                  │
│    40 │   │   │   local: bool = typer.Option(False, "--local", help="Use recommended local ser   │
│    41 │   │   ):                                                                                 │
│    42 │                                                                                          │
│ ❱  43 │   _run(                                                                                  │
│    44 │   │   server=server,                                                                     │
│    45 │   │   server_host=server_host,                                                           │
│    46 │   │   server_port=server_port,                                                           │
│                                                                                                  │
│ ╭────────────── locals ──────────────╮                                                           │
│ │                 client = False     │                                                           │
│ │            client_type = 'auto'    │                                                           │
│ │         context_window = 2048      │                                                           │
│ │                 expose = False     │                                                           │
│ │            llm_service = 'litellm' │                                                           │
│ │ llm_supports_functions = False     │                                                           │
│ │    llm_supports_vision = False     │                                                           │
│ │                  local = True      │                                                           │
│ │             max_tokens = 4096      │                                                           │
│ │                  model = 'gpt-4'   │                                                           │
│ │                 server = False     │                                                           │
│ │            server_host = '0.0.0.0' │                                                           │
│ │            server_port = 10001     │                                                           │
│ │             server_url = None      │                                                           │
│ │            stt_service = 'openai'  │                                                           │
│ │            temperature = 0.8       │                                                           │
│ │            tts_service = 'openai'  │                                                           │
│ │         tunnel_service = 'ngrok'   │                                                           │
│ ╰────────────────────────────────────╯                                                           │
│                                                                                                  │
│ F:\Katas\01\software\start.py:134 in _run                                                        │
│                                                                                                  │
│   131 │   │   │   │   except FileNotFoundError:                                                  │
│   132 │   │   │   │   │   client_type = "linux"                                                  │
│   133 │   │                                                                                      │
│ ❱ 134 │   │   module = importlib.import_module(f".clients.{client_type}.device", package='sour   │
│   135 │   │   client_thread = threading.Thread(target=module.main, args=[server_url])            │
│   136 │   │   client_thread.start()                                                              │
│   137                                                                                            │
│                                                                                                  │
│ ╭────────────────────────────────────── locals ───────────────────────────────────────╮          │
│ │                 client = True                                                       │          │
│ │            client_type = 'auto'                                                     │          │
│ │         context_window = 2048                                                       │          │
│ │                 expose = False                                                      │          │
│ │            handle_exit = <function _run.<locals>.handle_exit at 0x0000021AF5F5EA20> │          │
│ │            llm_service = 'litellm'                                                  │          │
│ │ llm_supports_functions = False                                                      │          │
│ │    llm_supports_vision = False                                                      │          │
│ │                  local = True                                                       │          │
│ │                   loop = <ProactorEventLoop running=True closed=False debug=False>  │          │
│ │             max_tokens = 4096                                                       │          │
│ │                  model = 'gpt-4'                                                    │          │
│ │                 server = True                                                       │          │
│ │            server_host = '0.0.0.0'                                                  │          │
│ │            server_port = 10001                                                      │          │
│ │          server_thread = <Thread(Thread-11 (run_until_complete), started 25900)>    │          │
│ │             server_url = '0.0.0.0:10001'                                            │          │
│ │            stt_service = 'local-whisper'                                            │          │
│ │            system_type = 'Windows'                                                  │          │
│ │            temperature = 0.8                                                        │          │
│ │            tts_service = 'piper'                                                    │          │
│ │         tunnel_service = 'ngrok'                                                    │          │
│ ╰─────────────────────────────────────────────────────────────────────────────────────╯          │
│                                                                                                  │
│ D:\Users\clt\anaconda3\Lib\importlib\__init__.py:126 in import_module                            │
│                                                                                                  │
│   123 │   │   │   if character != '.':                                                           │
│   124 │   │   │   │   break                                                                      │
│   125 │   │   │   level += 1                                                                     │
│ ❱ 126 │   return _bootstrap._gcd_import(name[level:], package, level)                            │
│   127                                                                                            │
│   128                                                                                            │
│   129 _RELOADING = {}                                                                            │
│                                                                                                  │
│ ╭────────────── locals ──────────────╮                                                           │
│ │ character = 'c'                    │                                                           │
│ │     level = 1                      │                                                           │
│ │      name = '.clients.auto.device' │                                                           │
│ │   package = 'source'               │                                                           │
│ ╰────────────────────────────────────╯                                                           │
│ in _gcd_import:1204                                                                              │
│ ╭──────────────── locals ────────────────╮                                                       │
│ │   level = 1                            │                                                       │
│ │    name = 'source.clients.auto.device' │                                                       │
│ │ package = 'source'                     │                                                       │
│ ╰────────────────────────────────────────╯                                                       │
│ in _find_and_load:1176                                                                           │
│ ╭──────────────────────── locals ────────────────────────╮                                       │
│ │ import_ = <function _gcd_import at 0x0000021AD2423D80> │                                       │
│ │  module = <object object at 0x0000021AD2454050>        │                                       │
│ │    name = 'source.clients.auto.device'                 │                                       │
│ ╰────────────────────────────────────────────────────────╯                                       │
│ in _find_and_load_unlocked:1126                                                                  │
│ ╭────────────────────────── locals ──────────────────────────╮                                   │
│ │     import_ = <function _gcd_import at 0x0000021AD2423D80> │                                   │
│ │        name = 'source.clients.auto.device'                 │                                   │
│ │      parent = 'source.clients.auto'                        │                                   │
│ │ parent_spec = None                                         │                                   │
│ │        path = None                                         │                                   │
│ ╰────────────────────────────────────────────────────────────╯                                   │
│ in _call_with_frames_removed:241                                                                 │
│ ╭────────────────────── locals ───────────────────────╮                                          │
│ │ args = ('source.clients.auto',)                     │                                          │
│ │    f = <function _gcd_import at 0x0000021AD2423D80> │                                          │
│ │ kwds = {}                                           │                                          │
│ ╰─────────────────────────────────────────────────────╯                                          │
│ in _gcd_import:1204                                                                              │
│ ╭──────────── locals ─────────────╮                                                              │
│ │   level = 0                     │                                                              │
│ │    name = 'source.clients.auto' │                                                              │
│ │ package = None                  │                                                              │
│ ╰─────────────────────────────────╯                                                              │
│ in _find_and_load:1176                                                                           │
│ ╭──────────────────────── locals ────────────────────────╮                                       │
│ │ import_ = <function _gcd_import at 0x0000021AD2423D80> │                                       │
│ │  module = <object object at 0x0000021AD2454050>        │                                       │
│ │    name = 'source.clients.auto'                        │                                       │
│ ╰────────────────────────────────────────────────────────╯                                       │
│ in _find_and_load_unlocked:1140                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │         child = 'auto'                                                                       │ │
│ │       import_ = <function _gcd_import at 0x0000021AD2423D80>                                 │ │
│ │          name = 'source.clients.auto'                                                        │ │
│ │        parent = 'source.clients'                                                             │ │
│ │ parent_module = <module 'source.clients' from                                                │ │
│ │                 'F:\\Katas\\01\\software\\source\\clients\\__init__.py'>                     │ │
│ │   parent_spec = ModuleSpec(name='source.clients',                                            │ │
│ │                 loader=<_frozen_importlib_external.SourceFileLoader object at                │ │
│ │                 0x0000021AF5F68CD0>,                                                         │ │
│ │                 origin='F:\\Katas\\01\\software\\source\\clients\\__init__.py',              │ │
│ │                 submodule_search_locations=['F:\\Katas\\01\\software\\source\\clients'])     │ │
│ │          path = ['F:\\Katas\\01\\software\\source\\clients']                                 │ │
│ │          spec = None                                                                         │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ModuleNotFoundError: No module named 'source.clients.auto'
Exception in thread Thread-11 (run_until_complete):
Traceback (most recent call last):
  File "D:\Users\clt\anaconda3\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "D:\Users\clt\anaconda3\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Users\clt\anaconda3\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "F:\Katas\01\software\source\server\server.py", line 414, in main
    service_instance = ServiceClass(config)
                       ^^^^^^^^^^^^^^^^^^^^
  File "F:\Katas\01\software\source\server\services\tts\piper\tts.py", line 12, in __init__
    self.install(config["service_directory"])
  File "F:\Katas\01\software\source\server\services\tts\piper\tts.py", line 38, in install
    OS = os.uname().sysname
         ^^^^^^^^
AttributeError: module 'os' has no attribute 'uname'. Did you mean: 'name'?
[IPKernelApp] WARNING | Parent appears to have exited, shutting down.
[IPKernelApp] WARNING | Parent appears to have exited, shutting down.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Python Version 3.11.18

All the best !
Pierre-Emmanuel

**Comment by bearstonem** [comment]
I don't think Windows is supported at this time. You can use Mac OS or use WSL

**Comment by zepef** [comment]
Hello [bearsyonem],

I think you are right, thanks. I will try to intall it under wsl.
All the best !

Pierre-Emmanuel
