### ISSUE TITLE
Is non-NVIDIA supported? Requirements ?

### ISSUE THREAD

**Issue by grigio** [OpenInterpreter/01#115]
**Describe the bug**
`poetry install` killed

```
  - Installing websockets (12.0)
  - Installing xmod (1.8.1)
zsh: killed     poetry install
 \uf312 \ue0b0 \uf07c ~/C/01/software \ue0b0 \uf113 \uf126 main \ue0b0 poetry install         \ue0b2 KILL \u2718 \ue0b2 5m 30s \uf252 
Installing dependencies from lock file

Package operations: 142 installs, 0 updates, 0 removals

  - Installing nvidia-cudnn-cu12 (8.9.2.26): Downloading... 99%
zsh: killed     poetry install
```

**Desktop (please complete the following information):**
CPU: 4x 1-core AMD Ryzen 7 7700 (-SMP-) speed: 3793 MHz
Kernel: 6.6.19-1-MANJARO x86_64 Up: 16m Mem: 3.41/3.83 GiB (89.0%)
Storage: 40 GiB (2026.8% used) Procs: 217 Shell: Zsh inxi: 3.3.33
Python 3.11.8

**Comment by matiyin** [comment]
weird I'm running it here without any GPU in a VM on my linux mint laptop. Works fine in openai mode. I would suggest maybe to try a fresh install. I had many issues with poetry install and had to solve other dependencies on my system first.

**Comment by tyfiero** [comment]
Thats a weird one, I haven't seen that. There should be no requirement for nvidia. Yeah try a fresh install, see if that helps

**Comment by grigio** [comment]
I close probably it happened because I had not enough ram
