### ISSUE TITLE
Incorrect Default Websocket Port in ESP Firmware

### ISSUE THREAD

**Issue by Cobular** [OpenInterpreter/01#122]
**Describe the bug**
The default websocket port in the esp32 client firmware is 80, should be setup to use the same port as the ping.

https://github.com/OpenInterpreter/01/blob/f9cc6bb66517991982cac0f9c05657e686eefb90/software/source/clients/esp32/src/client/client.ino#L671

I'm working on adding support for a new devkit I have on hand (ESP32-S3-BOX-Lite) so I'll have a larger PR ready for that soon but wanted to get this seen hopefully before first round consumer devices get flashed! (If this is even the codebase ya'll are using on the prod devices). 

Love the project 🧡

**Comment by Cobular** [comment]
Ok yeah that's a one line change, PR ready

**Comment by tyfiero** [comment]
Thanks for fixing it!

**Comment by tyfiero** [comment]
Does it still work for you?  I had it working by setting it to 80, (which is default for HTTP), but using the same port as the ping makes a lot of sense.

**Comment by Cobular** [comment]
It only works for me (macos) with the port matching the servers port!

**Comment by tyfiero** [comment]
Great! I'll merge the PR. Thanks
