### ISSUE TITLE
Doubt about the Point endpoint.

### ISSUE THREAD

**Issue by Mac0q** [OpenInterpreter/01#126]
Thanks for your contribution on the LLM!
Notice the computer api use the excellent endpoint, which been told that it would be open sourced in the past 1 or 2 weeks. To my limited knowledge, I cannot find the related information.
https://github.com/OpenInterpreter/open-interpreter/issues/1052

**Comment by tyfiero** [comment]
This is where the code lives:

https://github.com/OpenInterpreter/open-interpreter/tree/38a95aa9d30cdb0d72a637ddfedd7a20e8111cc5/interpreter/core/computer/display
