### ISSUE TITLE
Cannot call "receive" once a disconnect message has been received.

### ISSUE THREAD

**Issue by JayTing511** [OpenInterpreter/01#127]
(base) zhouxl@jiangliuerdeMacBook-Pro software % poetry run 01

○

Starting...

INFO:     Started server process [60460]
INFO:     Waiting for application startup.

Ready.

INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:10001 (Press CTRL+C to quit)
INFO:     ('127.0.0.1', 56406) - "WebSocket /" [accepted]
INFO:     connection open

Press the spacebar to start/stop recording. Press CTRL-C to exit.
Cannot call "receive" once a disconnect message has been received.
 Recording started...
Recording stopped.

seems nobody make this bug, only me, at least , i do not find any same bug in the upload issues.
someone knows how to solve it.

**Comment by oderwat** [comment]
> seems nobody make this bug, only me

I have the same behavior.

**Comment by DongTin** [comment]
Me too

**Comment by DongTin** [comment]
I found a [webpage](https://stackoverflow.com/questions/70933850/fastapi-websockets-runtimeerror-cannot-call-receive-once-a-disconnect-message) like this . It seems that the error message comes from fastapi.

**Comment by jacobrvl** [comment]
Does 01 work with the error? I can record something but don't get any response. I also checked my Openai token and it is never used. So I am sure it is not sending anything to openAI.

**Comment by DongTin** [comment]
> I have the same error. Does 01 work with the error for you? I can record something but don't get any response. I also checked my Openai token and it is never used. So I am sure it is not sending anything to openAI.

Yeah,record function is useful,but nothing happen when recording completed.

**Comment by DongTin** [comment]
By the way, I have this problem when using openai api, ollama and llmstudio.

**Comment by JayTing511** [comment]
> I have the same error. Does 01 work with the error for you? I can record something but don't get any response. I also checked my Openai token and it is never used. So I am sure it is not sending anything to openAI.

hh, i even can't record voice, Always looping between record started and record stopped.I am very confused and when i reset environment, it just repeat the looping. and have some other bugs.

**Comment by kieran-cr** [comment]
Same issue my side, unable to proceed after holding and releasing space bar to record audio

**Comment by ennis-ma** [comment]
Same error msg

**Comment by keldenl** [comment]
just want to chime in and i'm having this issue as well. m1 mac

**Comment by jacobrvl** [comment]
I solved my problem by switching from python version 3.9.2 to 3.11.8

**Comment by logimox** [comment]
> I solved my problem by switching from python version 3.9.2 to 3.11.8

How did you switch? Just update it?

**Comment by jacobrvl** [comment]
> > I solved my problem by switching from python version 3.9.2 to 3.11.8
> 
> How did you switch? Just update it?

I use [pyenv](https://github.com/pyenv/pyenv) to switch between different Python versions.

**Comment by oderwat** [comment]
I used `poetry env use 3.11` and `poetry install`. it worked after I created a dummy `REAME.md` file. Not sure why this is missing in my current setup.

**Comment by kieran-cr** [comment]
Issue appears linked with /Library/Caches/pypoetry/virtualenvs/01os-w_P9xt9H-py3.9/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

**Comment by keldenl** [comment]
thank you @oderwat !!!! i didn't have to create a readme file but here's what i did on my m1 pro

1. create a new conda env with python version 11.8, arm based 
```
CONDA_SUBDIR=osx-arm64 conda create -n 01 python python=3.11.8
```
2. `poetry install`

and that was it! now works :)

**Comment by tyfiero** [comment]
Did upgrading to python 3.11 fix this issue for folks?

**Comment by kieran-cr** [comment]
> I used `poetry env use 3.11` and `poetry install`. it worked after I created a dummy `REAME.md` file. Not sure why this is missing in my current setup.

This worked a treat on M1 Pro

**Comment by kieran-cr** [comment]
> Did upgrading to python 3.11 fix this issue for folks?

Oderwats instructions fixed my issue

**Comment by tyfiero** [comment]
I'm glad this solved the problem! If this issue arises again for anyone feel free to create a new issue

**Comment by rbrisita** [comment]
It has to do with the `websockets.connect` call and it's `ping_timeout` argument. PR forthcoming.
