### ISSUE TITLE
Slightly more convenient angles please <3 v1 body

### ISSUE THREAD

**Issue by Leopere** [OpenInterpreter/01#153]
**Describe the bug**
The whole setup is nice. As far as I can see, there are just some details, like the angles. If it could be 45º angles, more printers could print without support on the outer rim, guaranteeing more printers could do the threading.

**Expected behavior**
Just that easier printing is always nice for everyone.

**Screenshots**
<img width="526" alt="image" src="https://github.com/OpenInterpreter/01/assets/1068374/d13f87ce-ee85-4d37-8f4e-4d3f6aad49df">

**Desktop (please complete the following information):**
- AFK

**Additional context**
Everything is wonderful just nitpicking for usability reasons.

**Comment by tyfiero** [comment]
Great call out. This is something we should address in future 3D models, feel free to make a PR with a better version! We will keep this in mind for upcoming models. I'm going to close this for now, but if anyone out there wants to help make the model more print-friendly feel free to open a new issue.
