### ISSUE TITLE
When pressing spacebar, nothing happens."

### ISSUE THREAD

**Issue by miguelhg9211** [OpenInterpreter/01#171]
I installed everything without any problem, but when starting the dialog and pressing spacebar, nothing happens, nothing is recorded, I have Linux Ubuntu 22.04.4 LTS.

**Comment by hugoblanc** [comment]
Basically you need to focus another window

**Comment by hugoblanc** [comment]
At least on mac, I first thought it was not working, and when I started writing comment on github I saw Mac asking for microphone authorization. Because I was pressing space bar

**Comment by tyfiero** [comment]
@miguelhg9211 Can you post what logs you are seeing? It might be a permissions thing

**Comment by miguelhg9211** [comment]
I've already fixed it by opening a terminal in Visual Studio Code, however, the open interpreter performs actions I haven't commanded or does incoherent things. I don't know if it's because I'm using GPT 3.5 Turbo.

**Comment by tyfiero** [comment]
Im glad that fixed it! Yeah, 3.5 turbo is lacking in quality. Unfortunately GPT-4 is still the best performing model in OI.

**Comment by kill136** [comment]
> I installed everything without any problem, but when starting the dialog and pressing spacebar, nothing happens, nothing is recorded, I have Linux Ubuntu 22.04.4 LTS.

hi, are you  running in wsl2 ? how can you enter backspace make it works?
