### ISSUE TITLE
evdev failing when doing petry install.

### ISSUE THREAD

**Issue by cllamasm** [OpenInterpreter/01#172]
**Describe the bug**
evdev not installing when doing poetry install.

**To Reproduce**
When I try to execute "poetry install" it fails because of evdev.

**Expected behavior**

**Screenshots**
![image](https://github.com/OpenInterpreter/01/assets/126588704/195c0069-bc2e-4fd7-af5b-fb7dc901b7e0)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Python Version: 3.8.10

**Comment by TashaSkyUp** [comment]
Can you try with python 3.10?

**Comment by tyfiero** [comment]
The 01 repository requires python 3.11, please retry with python 3.11. pyenv makes it easy to try different versions of python

**Comment by tyfiero** [comment]
Closing this issue for now. Please comment here if python 3.11 does not work for you @cllamasm
