### ISSUE TITLE
Hello, friend! Can you provide me with some guidance on how to develop and debug this project? I am currently using VS Code and PyCharm, but I don't know how to debug correctly. Who can give me some guidance and help? Thank you very much.

### ISSUE THREAD

**Issue by kill136** [OpenInterpreter/01#195]
Hello, friend! Can you provide me with some guidance on how to develop and debug this project? I am currently using VS Code and PyCharm, but I don't know how to debug correctly. Who can give me some guidance and help? Thank you very much.
![image](https://github.com/OpenInterpreter/01/assets/22001343/99f6f73f-05ac-4cd9-9f60-7c0d0dc728e1)
![image](https://github.com/OpenInterpreter/01/assets/22001343/f8ca80da-58d2-4e8a-8d35-a9fc6fc77dfb)

**Comment by tyfiero** [comment]
I'm not familiar with pycharm, so I'm not of much help there. Although I can see you are trying to use it with python 3.10. Please try python 3.11! pyenv makes it easy to switch

**Comment by kill136** [comment]
> I'm not familiar with pycharm, so I'm not of much help there. Although I can see you are trying to use it with python 3.10. Please try python 3.11! pyenv makes it easy to switch

thanks ,dear, what kinds  of develop tool you using? i want try it

**Comment by tyfiero** [comment]
I use Cursor, the AI powered VSCode! It works great.

**Comment by kill136** [comment]
> I use Cursor, the AI powered VSCode! It works great.

how debugger our project  with vscode , i dont known ,could you help me?

**Comment by tyfiero** [comment]
I am not familiar with VScode debugging.Maybe the VSCode docs can help you?

https://code.visualstudio.com/Docs/editor/debugging
