### ISSUE TITLE
ISSUE With poetry run 01 --server --expose 

### ISSUE THREAD

**Issue by tajakmal** [OpenInterpreter/01#199]
When running poetry run 01 --server --expose I get two errors or callouts. One in the terminal that says: 

`○                                                                                                      

Starting...                                                                                            

Exposing server to the internet...                                                                     

INFO:     Started server process [37924]
INFO:     Waiting for application startup.

Ready.                                                                                                 

INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:10001 (Press CTRL+C to quit)

Your server is being hosted at the following URL: https://2f7e-67-205-253-220.ngrok-free.app
INFO:     67.205.253.220:0 - "GET / HTTP/1.1" 405 Method Not Allowed
INFO:     67.205.253.220:0 - "GET /favicon.ico HTTP/1.1" 404 Not Found`

The other on the browser:
`{"detail":"Method Not Allowed"}`

**Expected behavior**
I wanted to test out before soldering everything together.

**Screenshots**
<img width="399" alt="Screenshot 2024-03-30 at 9 40 33 AM" src="https://github.com/OpenInterpreter/01/assets/17787788/183809f9-9b8a-437d-9e8a-d6c8475ec121">
<img width="680" alt="Screenshot 2024-03-30 at 9 40 26 AM" src="https://github.com/OpenInterpreter/01/assets/17787788/9948bef1-4541-4acb-ab4a-187c7a2fb828">

**Desktop (please complete the following information):**
 - OS: MacOS - Sonoma
 - Python Version: 3.11.4

**Comment by tyfiero** [comment]
There is no GET endpoint for the 01 repo, it all happens over websockets. When you paste the link in the browser it just makes a GET request, as you can see in the logs. You can try the library https://github.com/vi/websocat to test the websocket in your CLI!

**Comment by tajakmal** [comment]
You’re right - totally missed lol but yes I have everything working!
