### ISSUE TITLE
Implement 'Interrupt' logic

### ISSUE THREAD

**Issue by human-bee** [OpenInterpreter/01#62]
Being able to interrupt when it is speaking and start speaking to it again immediately.

@TomChapin do you know where the progress is currently at?

**Comment by tomchapin** [comment]
Where I last left off on this task, I was running into a bunch of issues with playing the audio asynchronously, and with terminating it in the middle of it playing a sound. The audio library we were using wasn’t working properly with asyncio.

So essentially, this issue hasn’t been resolved yet (unless someone else has figured out the solution)

**Comment by human-bee** [comment]
Tricky Bermuda Triangle - Need to figure out when to interrupt (while writing code?)/buffers necessary
