### ISSUE TITLE
[Feature request] I want to run 01 on meta ray bans

### ISSUE THREAD

**Issue by jetjodh** [OpenInterpreter/01#94]
I would wanna run 01 stack on my meta ray ban hardware or thru a web socket connection which can accept commands from meta assistant.

**Comment by tyfiero** [comment]
This would be so cool! As far as I can tell, Meta does not allow you to make apps on the platform, I don't think we can make this one happen. It's won't be on our official roadmap, but if you can figure out a way to do it, feel free to make a pull request to add it as a client.
