### ISSUE TITLE
feat: Add full CLI support

### ISSUE THREAD

**Issue by cutmasta-kun** [OpenInterpreter/01#95]
I know, that a lot of use-cases will revolve around "Open this Application, do that, etc" but I don't get why 01OS at the moment only supports Mac and Linux. 
The audio, display and command-line complications may be a reason to support only unix types right now, but I don't see any reason why a CLI only Client and Server shouldn't be possible. At the moment it's quite painful to run this in a WSL2 Ubuntu env, I guess installing and suffering through pulse-audio may be the way.

If I didn't read the documentation enough, I'm sorry if it's already possible to do that.

**Comment by tyfiero** [comment]
You can use it fully in the CLI by just running `poetry run 01`, and then using the spacebar as the 'button'. If you run into issues with this, please open a new issue!
